
spring:
  application:
    name: product
  rabbitmq:
    host: 192.168.27.140
    port: 5672
    password: guest
    username: guest
  jackson:
    default-property-inclusion: non_null  #如果返回值为null，则不返回
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/lpp?useSSL=false
  jpa:
    show-sql: true
server:
  port: 8081



