
spring:
  application:
    name: gatewey
  jackson:
    default-property-inclusion: non_null  #如果返回值为null，则不返回
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/lpp?useSSL=false
  jpa:
    show-sql: true
server:
  port: 9000
  
zuul:
  routes:  #配置自定义的接口
     myProduct:
       path: /myProduct/**  #指定请求路径
       serviceId: product  #指定服务名称
       sensitiveHeaders:  #敏感头部，设置为空，否则将会过滤到cookie

  ignored-patterns:  #排除指定请求路径，例：
    - /**/test/







